#!/bin/sh

WAL_PATH="${HOME}/.local/bin/wal"
ROFI_WAL_PATH="${HOME}/.config/rofi/scripts/pywal.sh"

set_wallpaper_hyprland() {
	echo $PATH
    dir="${HOME}/Pictures/wallpapers"
    input_path="$1"
    PROGRAM="swww-daemon"
    transition_type="center"

    if [ -n "$input_path" ] && [ -f "$input_path" ]; then
        BG="$input_path"
    else
        BG="$(find "$dir" -name '*.jpg' -o -name '*.png' -o -name '*.jpeg' | shuf -n1)"
    fi

    if pgrep "$PROGRAM" >/dev/null; then
        swww img "$BG" --transition-fps 244 --transition-type $transition_type --transition-duration 1
    else
        swww-daemon && swww img "$BG" --transition-fps 244 --transition-type $transition_type --transition-duration 1 
    fi
	
    $WAL_PATH -n --cols16 lighten --contrast 4 -i "$BG"
    $ROFI_WAL_PATH

    # Set same image for hyprlock
    LOCKSCREEN_BG_PATH="${HOME}/.config/lockscreenbg"
    ln -sf "$BG" "$LOCKSCREEN_BG_PATH"

    # Wallpaper for wlogout
    cp "$BG" "${HOME}/.config/wlogout/bg.jpg"

    # Wallpaper for wlogout (blurred)
    # convert "$BG" -blur 0x8 "${HOME}/.config/wlogout/bg.jpg"

    ${HOME}/.config/hypr/scripts/restart-waybar.sh
}

set_wallpaper_hyprland "$1"
