
$image = 641193.jpg
$background = rgba(0f1512ff)

$image = 641193.jpg
$error = rgba(ffb4abff)

$image = 641193.jpg
$error_container = rgba(93000aff)

$image = 641193.jpg
$inverse_on_surface = rgba(2c322fff)

$image = 641193.jpg
$inverse_primary = rgba(136b56ff)

$image = 641193.jpg
$inverse_surface = rgba(dee4dfff)

$image = 641193.jpg
$on_background = rgba(dee4dfff)

$image = 641193.jpg
$on_error = rgba(690005ff)

$image = 641193.jpg
$on_error_container = rgba(ffdad6ff)

$image = 641193.jpg
$on_primary = rgba(00382bff)

$image = 641193.jpg
$on_primary_container = rgba(a3f2d7ff)

$image = 641193.jpg
$on_primary_fixed = rgba(002118ff)

$image = 641193.jpg
$on_primary_fixed_variant = rgba(00513fff)

$image = 641193.jpg
$on_secondary = rgba(1e352dff)

$image = 641193.jpg
$on_secondary_container = rgba(cee9ddff)

$image = 641193.jpg
$on_secondary_fixed = rgba(072019ff)

$image = 641193.jpg
$on_secondary_fixed_variant = rgba(344c43ff)

$image = 641193.jpg
$on_surface = rgba(dee4dfff)

$image = 641193.jpg
$on_surface_variant = rgba(bfc9c3ff)

$image = 641193.jpg
$on_tertiary = rgba(0d3446ff)

$image = 641193.jpg
$on_tertiary_container = rgba(c4e7ffff)

$image = 641193.jpg
$on_tertiary_fixed = rgba(001e2cff)

$image = 641193.jpg
$on_tertiary_fixed_variant = rgba(284b5dff)

$image = 641193.jpg
$outline = rgba(89938eff)

$image = 641193.jpg
$outline_variant = rgba(3f4945ff)

$image = 641193.jpg
$primary = rgba(87d6bcff)

$image = 641193.jpg
$primary_container = rgba(00513fff)

$image = 641193.jpg
$primary_fixed = rgba(a3f2d7ff)

$image = 641193.jpg
$primary_fixed_dim = rgba(87d6bcff)

$image = 641193.jpg
$scrim = rgba(000000ff)

$image = 641193.jpg
$secondary = rgba(b2ccc1ff)

$image = 641193.jpg
$secondary_container = rgba(344c43ff)

$image = 641193.jpg
$secondary_fixed = rgba(cee9ddff)

$image = 641193.jpg
$secondary_fixed_dim = rgba(b2ccc1ff)

$image = 641193.jpg
$shadow = rgba(000000ff)

$image = 641193.jpg
$source_color = rgba(a9b2adff)

$image = 641193.jpg
$surface = rgba(0f1512ff)

$image = 641193.jpg
$surface_bright = rgba(343b38ff)

$image = 641193.jpg
$surface_container = rgba(1b211eff)

$image = 641193.jpg
$surface_container_high = rgba(252b29ff)

$image = 641193.jpg
$surface_container_highest = rgba(303633ff)

$image = 641193.jpg
$surface_container_low = rgba(171d1aff)

$image = 641193.jpg
$surface_container_lowest = rgba(090f0dff)

$image = 641193.jpg
$surface_dim = rgba(0f1512ff)

$image = 641193.jpg
$surface_tint = rgba(87d6bcff)

$image = 641193.jpg
$surface_variant = rgba(3f4945ff)

$image = 641193.jpg
$tertiary = rgba(a8cbe2ff)

$image = 641193.jpg
$tertiary_container = rgba(284b5dff)

$image = 641193.jpg
$tertiary_fixed = rgba(c4e7ffff)

$image = 641193.jpg
$tertiary_fixed_dim = rgba(a8cbe2ff)

